spring.application.name=paybandhu
server.port= 8081

spring.datasource.url=jdbc:postgresql://ep-crimson-recipe-ao3c8klt-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zVFxcW1R6HCs

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


