spring.application.name=paybandhu


spring.datasource.url=jdbc:postgresql://ep-dry-base-aokd87ik-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=password Neon

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


git add src/main/java/paybandhu/agent
git add src/main/java/paybandhu/common
git add src/main/resources/application.properties
git add pom.xml